### ISSUE TITLE
Query about task persistence in celery job queue

### ISSUE THREAD

**Issue by aswad546** [wspr-ncsu/visiblev8-crawler#7]
This is more a query than an issue, am I correct in understanding that the job queue between the backend and the workers is not persistent, i.e. the container goes down then the queue will lose messages and not continue where it left off. If this is true why did you make this design choice. If I am mistaken please point me to the part of the system that handles persistence in the redis broker.

**Comment by sohomdatta1** [comment]
```yaml
task_queue_broker:
    restart: unless-stopped
    image: redis:6.2
    volumes:
      - ./redis_data:/data
  ```
in `docker-compose.yaml` writes the redis queue to the `./redis_data` directory. This should allow for persisting state across restarts, though this should not be relied on since you can end up with invalid celery task states.
